### ISSUE TITLE
Impossible de lancer le nouveau client sur une machine WSL sur W11

### ISSUE THREAD

**Issue by biskweet** [cbouilla/uglix4-public#2]
La mise à jour du client (postée il y a ~1.5 mois) ne se lance pas sur une machine WSL avec Python 3.10.12.
```
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3296
```
Erreur :
```
ALSA lib confmisc.c:855:(parse_card) cannot find card '0'
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_card_inum returned error: No such file or directory
ALSA lib confmisc.c:422:(snd_func_concat) error evaluating strings
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1334:(snd_func_refer) error evaluating name
ALSA lib conf.c:5178:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5701:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2664:(snd_pcm_open_noupdate) Unknown PCM default
Unhandled Error
Traceback (most recent call last):
  File "/mnt/c/Users/x/Documents/Ecole/tme-crypto/venv/lib/python3.10/site-packages/twisted/python/log.py", line 96, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/mnt/c/Users/x/Documents/Ecole/tme-crypto/venv/lib/python3.10/site-packages/twisted/python/log.py", line 80, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/mnt/c/Users/x/Documents/Ecole/tme-crypto/venv/lib/python3.10/site-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/mnt/c/Users/x/Documents/Ecole/tme-crypto/venv/lib/python3.10/site-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
--- <exception caught here> ---
  File "/mnt/c/Users/x/Documents/Ecole/tme-crypto/venv/lib/python3.10/site-packages/twisted/internet/posixbase.py", line 482, in _doReadOrWrite
    why = selectable.doRead()
  File "/mnt/c/Users/x/Documents/Ecole/tme-crypto/venv/lib/python3.10/site-packages/twisted/internet/tcp.py", line 248, in doRead
    return self._dataReceived(data)
  File "/mnt/c/Users/x/Documents/Ecole/tme-crypto/venv/lib/python3.10/site-packages/twisted/internet/tcp.py", line 253, in _dataReceived
    rval = self.protocol.dataReceived(data)
  File "/mnt/c/Users/x/Documents/Ecole/tme-crypto/venv/lib/python3.10/site-packages/twisted/conch/telnet.py", line 591, in dataReceived
    self.negotiate(commands)
  File "/mnt/c/Users/x/Documents/Ecole/tme-crypto/venv/lib/python3.10/site-packages/twisted/conch/telnet.py", line 640, in negotiate
    cmdFunc(data)
  File "/mnt/c/Users/x/Documents/Ecole/tme-crypto/client.py", line 157, in telnet_PLUGIN
    exec(zlib.decompress(b''.join(data)))
  File "<string>", line 88, in <module>

  File "<string>", line 81, in setup_plugins

  File "<string>", line 20, in __init__

builtins.ValueError: Mix_OpenAudio: b"ALSA: Couldn't open audio device: No such file or directory"
```

**Comment by cbouilla** [comment]
Ce problème de son sous WSL est dur à régler. Solution : laisser tomber WSL !

**Comment by biskweet** [comment]
Dommage, ça fonctionnait sur l'ancienne version :(
